name: Linux GCC

on: [pull_request]

concurrency:
  group: ${{ github.ref }}-${{ github.head_ref }}-linux-gcc
  cancel-in-progress: true

jobs:
  library:
    name: GNU@9.3 C++17 Release
    runs-on: ubuntu-20.04
    # env: {CXXFLAGS: "-fno-operator-names -Werror -Wall -Wextra -Wpedantic -Wnull-dereference -Wfloat-conversion -Wshadow -Woverloaded-virtual"}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install Dependencies
      run: Submodules/AMReX/.github/workflows/dependencies/dependencies.sh

    - name: Install CCache
      run: Submodules/AMReX/.github/workflows/dependencies/dependencies_ccache.sh

    - name: Set Up Cache
      uses: actions/cache@v4
      with:
        path: ~/.cache/ccache
        key: ccache-${{ github.workflow }}-${{ github.job }}-git-${{ github.sha }}
        restore-keys: |
             ccache-${{ github.workflow }}-${{ github.job }}-git-

    - name: Configure Project and Generate Build System
      run: |
        export CCACHE_COMPRESS=1
        export CCACHE_COMPRESSLEVEL=10
        export CCACHE_MAXSIZE=300M
        ccache -z

        cmake \
          -B${{runner.workspace}}/REMORA/build \
          -DCMAKE_INSTALL_PREFIX:PATH=${{runner.workspace}}/REMORA/install \
          -DCMAKE_BUILD_TYPE:STRING=Debug \
          -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
          -DREMORA_DIM:STRING=3 \
          -DREMORA_ENABLE_MPI:BOOL=ON \
          -DREMORA_ENABLE_TESTS:BOOL=ON \
          -DREMORA_ENABLE_ALL_WARNINGS:BOOL=ON \
          -DREMORA_ENABLE_FCOMPARE:BOOL=ON \
          ${{github.workspace}};

        ccache -s
        du -hs ~/.cache/ccache

    - name: Compile and Link
      run: |
        cmake --build ${{runner.workspace}}/REMORA/build --parallel 2 --verbose

    - name: CMake Tests # see file REMORA/Tests/CTestList.cmake
      run: |
        ctest -L regression -VV
      working-directory: ${{runner.workspace}}/REMORA/build
