name: REMORA CI (sycl)

on:
  pull_request:
    branches: [development]

concurrency:
  group: ${{ github.ref }}-${{ github.head_ref }}-sycl
  cancel-in-progress: true

jobs:
  Build-And-Test-SYCL:
    name: oneAPI SYCL
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Dependencies
      run: Submodules/AMReX/.github/workflows/dependencies/dependencies_dpcpp.sh

    - name: Install CCache
      run: Submodules/AMReX/.github/workflows/dependencies/dependencies_ccache.sh

    - name: Set Up Cache
      uses: actions/cache@v4
      with:
        path: ~/.cache/ccache
        key: ccache-${{ github.workflow }}-${{ github.job }}-git-${{ github.sha }}
        restore-keys: |
             ccache-${{ github.workflow }}-${{ github.job }}-git-

    - name: Build
      run: |
        export CCACHE_COMPRESS=1
        export CCACHE_COMPRESSLEVEL=10
        export CCACHE_MAXSIZE=250M
        export CCACHE_DEPEND=1
        ccache -z

        set +e
        source /opt/intel/oneapi/setvars.sh
        set -e
        mkdir build
        cd build
        cmake .. \
          -DCMAKE_VERBOSE_MAKEFILE=ON                   \
          -DCMAKE_INSTALL_PREFIX:PATH=${{runner.workspace}}/REMORA/install \
          -DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo \
          -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
          -DREMORA_DIM:STRING=3 \
          -DREMORA_ENABLE_MPI:BOOL=ON \
          -DREMORA_ENABLE_SYCL:BOOL=ON \
          -DREMORA_ENABLE_TESTS:BOOL=ON \
          -DREMORA_ENABLE_ALL_WARNINGS:BOOL=ON \
          -DREMORA_ENABLE_FCOMPARE:BOOL=ON \
          -DCMAKE_C_COMPILER=$(which icx) \
          -DCMAKE_CXX_COMPILER=$(which icpx) \
          -DCMAKE_CXX_STANDARD=17
        make -j 2

        ccache -s
        du -hs ~/.cache/ccache
